<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'ATTR_FILE' => 'ID',
    'ATTR_OPTION_MERGE' => 'Merge IP by mask',
    'ATTR_IP' => 'IP',
    'ATTR_VISITS' => 'Visits',
    'ATTR_CLICKS' => 'Clicks',
    'ATTR_CONVERSIONS' => 'Conversions',
    'ATTR_REVENUE' => 'Revenue',
    'ATTR_COST' => 'Cost',
    'ATTR_PROFIT' => 'Profit',
    'ATTR_CPV' => 'CPV',
    'ATTR_CTR' => 'CTR',
    'ATTR_CR' => 'CR',
    'ATTR_CV' => 'CV',
    'ATTR_ROI' => 'ROI',
    'ATTR_EPV' => 'EPV',
    'BTN_UPLOAD_FILE' => 'Upload',
    'BTN_EXTRACTS_IP' => 'Extracts IP',
    'INDEX_TITLE' => 'Ip range table',
    'MENU_TITLE' => 'Ip range',
];
